general_sym_project_homepage:
    path:  /
    defaults: { _controller: GeneralSymProjectBundle:Page:index }

general_sym_project_about:
    path:  /about
    defaults: { _controller: GeneralSymProjectBundle:Page:about }
    requirements:
        _methods:  GET

general_sym_project_show:
    path:  /{id}/{slug}
    defaults: { _controller: GeneralSymProjectBundle:Blog:show }
    requirements:
        _methods:  GET
        id: \d+

general_sym_project_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: GeneralSymProjectBundle:Comment:create }
    requirements:
        _methods:  POST
        blog_id:  \d+

general_sym_project_monthly:
     path:  /archive/{year}/{month}
     defaults: { _controller: GeneralSymProjectBundle:Page:showByMonth }

general_sym_project_search:
    path: /search
    defaults: { _controller: GeneralSymProjectBundle:Page:search }