parameters:
#    general_sym_project.example.class: General\SymProjectBundle\Example

services:
#    general_sym_project.example:
#        class: %general_sym_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
